name: Assemble Release apk

on:
  pull_request:
    branches:
      - master
      - ColdRain-Moro/ci_test

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install python requests
        run: pip install requests

      - name: create secret file
        run: python ./.github/scripts/create_secret.py "$BUGLY_APP_ID" "$SOPHIX_APP_ID" "$SOPHIX_APP_SECRET" "$SOPHIX_RSA" "$UM_APP_KEY" "$UM_PUSH_SECRET" "$UM_SHARE_SINA_APP_KEY" "$UM_SHARE_SINA_APP_SECRET" "$UM_SHARE_QQ_ZONE_APP_ID" "$UM_SHARE_QQ_ZONE_APP_SECRET" "$amap_apikey" "$RELEASE_KEY_ALIAS" "$RELEASE_KEY_PASSWORD" "$RELEASE_STORE_PASSWORD" "$KEY_CYXBS_URL"
        env:
          BUGLY_APP_ID: ${{secrets.BUGLY_APP_ID}}
          SOPHIX_APP_ID: ${{secrets.SOPHIX_APP_ID }}
          SOPHIX_APP_SECRET: ${{secrets.SOPHIX_APP_SECRET}}
          SOPHIX_RSA: ${{secrets.SOPHIX_RSA}}
          UM_APP_KEY: ${{secrets.UM_APP_KEY}}
          UM_PUSH_SECRET: ${{secrets.UM_PUSH_SECRET}}
          UM_SHARE_SINA_APP_KEY: ${{secrets.UM_SHARE_SINA_APP_KEY}}
          UM_SHARE_SINA_APP_SECRET: ${{secrets.UM_SHARE_SINA_APP_SECRET}}
          UM_SHARE_QQ_ZONE_APP_ID: ${{secrets.UM_SHARE_QQ_ZONE_APP_ID}}
          UM_SHARE_QQ_ZONE_APP_SECRET: ${{secrets.UM_SHARE_QQ_ZONE_APP_SECRET}}
          amap_apikey: ${{secrets.amap_apikey}}
          RELEASE_KEY_ALIAS: ${{secrets.RELEASE_KEY_ALIAS}}
          RELEASE_KEY_PASSWORD: ${{secrets.RELEASE_KEY_PASSWORD}}
          RELEASE_STORE_PASSWORD: ${{secrets.RELEASE_STORE_PASSWORD}}
          KEY_CYXBS_URL: ${{secrets.KEY_CYXBS_URL}}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew channelRelease
      
      - name: Generate release json
        run: python ./.github/scripts/generate_release_json.py "$RELEASE_BASE_URL" "$RELEASE_TOKEN" "$UPDATE_CONTENT"
        env:
          RELEASE_BASE_URL: ${{ secrets.RELEASE_BASE_URL }}
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          UPDATE_CONTENT: ${{ github.event.pull_request.body }}

      - name: Archive release json
        uses: actions/upload-artifact@v2
        with:
          name: release_json
          path: release.json
          retention-days: 15